feat: (refactor) introduce uuv-cli engine from runner-commons, #576
Orange-OpenSource/uuv pull request #577
Opened 2024-04-10 20:01 UTC by luifr10

2024-04-15 18:14 UTC, luifr10 commented on packages/runner-playwright/src/lib/runner-playwright.ts
> +            configFile,
Doesn't came from user input

2024-04-18 19:27 UTC, stanlee974 requested changes

2024-04-18 19:27 UTC, stanlee974 commented on packages/runner-commons/src/cli/helper.ts
> +        if (!isNull(targetTestFile) && !isEmpty(targetTestFile)) {
IsEmpty gère le null. C'est donc suffisant et on peut enlever isNull

2024-04-18 19:27 UTC, stanlee974 commented on packages/runner-commons/src/cli/helper.ts
> +    static deleteAllFileOfDirectory(dirPath) {
Me semble qu'on a un helper pour ça ailleurs. Il faudrait deplacer

2024-04-18 19:27 UTC, stanlee974 commented on packages/runner-commons/src/cli/options.ts
> +export interface UUVCliOptions {
Le changer en type si possible

2024-04-18 19:27 UTC, stanlee974 commented on packages/runner-commons/src/cli/engine.ts
> +export class UUVCliEngine {
En static ça peut être pas mal

2024-04-18 19:27 UTC, stanlee974 commented on packages/runner-playwright/src/lib/runner-playwright.ts
> +    private getTargetTestFileForPlawright(targetTestFile?: string): string {
Manque un y à playwright

2024-04-18 19:46 UTC, luifr10 commented on packages/runner-commons/src/cli/options.ts
> +export interface UUVCliOptions {
Corrigé

2024-04-18 19:47 UTC, luifr10 commented on packages/runner-commons/src/cli/helper.ts
> +        if (!isNull(targetTestFile) && !isEmpty(targetTestFile)) {
Corrigé

2024-04-18 19:49 UTC, luifr10 commented on packages/runner-playwright/src/lib/runner-playwright.ts
> +    private getTargetTestFileForPlawright(targetTestFile?: string): string {
Corrigé

2024-04-18 19:54 UTC, luifr10 commented on packages/runner-commons/src/cli/helper.ts
> +    static deleteAllFileOfDirectory(dirPath) {
Corrigé

2024-04-21 22:41 UTC, luifr10 commented on packages/runner-commons/src/cli/engine.ts
> +export class UUVCliEngine {
Conservé non static pour le moment

2024-04-22 11:31 UTC, merged